# Dummy Experiment

Dummy notebook demonstrating how to import tools from the environment and run a simple Supervised Fine-Tuning (SFT) workflow. Intended purely for illustrative purposes.

In [ ]:
!git clone --branch feat/experiment1 --single-branch https://github.com/YassKa71/AI_agents_mini_project.git
%cd AI_agents_mini_project

Cloning into 'AI_agents_mini_project'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 66 (delta 19), reused 63 (delta 16), pack-reused 0 (from 0)
Receiving objects: 100% (66/66), 921.80 KiB | 3.91 MiB/s, done.
Resolving deltas: 100% (19/19), done.
/content/AI_agents_mini_project

In [ ]:
!pip install -e .

Obtaining file:///content/AI_agents_mini_project
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ai_agents_mini_project==0.1.0) (1.12.0)
Collecting bitsandbytes>=0.49.1 (from ai_agents_mini_project==0.1.0)
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting datasets>=4.5.0 (from ai_agents_mini_project==0.1.0)
  Downloading datasets-4.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: jinja2>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ai_agents_mini_project==0.1.0) (3.1.6)
Collecting pandas>=2.3.3 (from ai_agents_mini_project==0.1.0)
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 9.6 MB/s eta 0:00:00
Collecting peft>=0.18.1 (from ai_agents_mini_project==0.1.0)
  Downloading peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Collecting pytest>=9.0.2 (from ai_agents_mini_project==0.1.0)
  Downloading pytest-9.0.2-py3-none-any.whl.metadata (7.6 kB)
Collecting rapidfuzz>=3.14.3 (from ai_agents_mini_project==0.1.0)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting torch>=2.9.1 (from ai_agents_mini_project==0.1.0)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting transformers>=4.57.5 (from ai_agents_mini_project==0.1.0)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.7 MB/s eta 0:00:00
Collecting trl>=0.27.0 (from ai_agents_mini_project==0.1.0)
  Downloading trl-0.27.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (3.20.2)
Collecting pyarrow>=21.0.0 (from datasets>=4.5.0->ai_agents_mini_project==0.1.0)
  Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.5.0->ai_agents_mini_project==0.1.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (2025.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.1.6->ai_agents_mini_project==0.1.0) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.3->ai_agents_mini_project==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.3->ai_agents_mini_project==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.3.3->ai_agents_mini_project==0.1.0) (2025.3)
Requirement already satisfied: iniconfig>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from pytest>=9.0.2->ai_agents_mini_project==0.1.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=9.0.2->ai_agents_mini_project==0.1.0) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=9.0.2->ai_agents_mini_project==0.1.0) (2.19.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (3.6.1)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (9.10.2.21)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.9.1->ai_agents_mini_project==0.1.0) (3.3.20)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch>=2.9.1->ai_agents_mini_project==0.1.0)
  Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.5->ai_agents_mini_project==0.1.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.57.5->ai_agents_mini_project==0.1.0) (0.22.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.12.0->ai_agents_mini_project==0.1.0) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.3.3->ai_agents_mini_project==0.1.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.9.1->ai_agents_mini_project==0.1.0) (1.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets>=4.5.0->ai_agents_mini_project==0.1.0) (1.22.0)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 36.0 MB/s eta 0:00:00
Downloading datasets-4.5.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 41.2 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 143.7 MB/s eta 0:00:00
Downloading peft-0.18.1-py3-none-any.whl (556 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 49.8 MB/s eta 0:00:00
Downloading pytest-9.0.2-py3-none-any.whl (374 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.8/374.8 kB 37.0 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 87.9 MB/s eta 0:00:00
Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl (899.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 1.7 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 1.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 153.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 26.5 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 49.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 4.5 MB/s eta 0:00:00
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 76.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 36.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 3.0 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 3.2 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 59.6 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 9.4 MB/s eta 0:00:00
Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.6 MB/s eta 0:00:00
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 159.2 MB/s eta 0:00:00
Downloading trl-0.27.0-py3-none-any.whl (532 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.5/532.5 kB 38.8 MB/s eta 0:00:00
Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 48.4 MB/s eta 0:00:00
Building wheels for collected packages: ai_agents_mini_project
  Building editable for ai_agents_mini_project (pyproject.toml) ... done
  Created wheel for ai_agents_mini_project: filename=ai_agents_mini_project-0.1.0-0.editable-py3-none-any.whl size=1792 sha256=0e0360de59c7d87d66eb49ce8db60d79b77ffba88a6fa61efe0ca6392770f993
  Stored in directory: /tmp/pip-ephem-wheel-cache-yyob5asj/wheels/06/fb/a8/d6e9e7f54ab3110430c3b49c7467315dae0f400b4c5e2a1535
Successfully built ai_agents_mini_project
Installing collected packages: triton, rapidfuzz, pytest, pyarrow, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, pandas, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cusolver-cu12, transformers, torch, datasets, bitsandbytes, trl, peft, ai_agents_mini_project
  Attempting uninstall: triton
    Found existing installation: triton 3.5.0
    Uninstalling triton-3.5.0:
      Successfully uninstalled triton-3.5.0
  Attempting uninstall: pytest
    Found existing installation: pytest 8.4.2
    Uninstalling pytest-8.4.2:
      Successfully uninstalled pytest-8.4.2
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.6.77
    Uninstalling nvidia-nvtx-cu12-12.6.77:
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.6.85
    Uninstalling nvidia-nvjitlink-cu12-12.6.85:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.6.85
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufile-cu12
    Found existing installation: nvidia-cufile-cu12 1.11.1.6
    Uninstalling nvidia-cufile-cu12-1.11.1.6:
      Successfully uninstalled nvidia-cufile-cu12-1.11.1.6
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.77
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.4.1
    Uninstalling nvidia-cublas-cu12-12.6.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4

In [ ]:
# IMPORTANT: You need to restart the session in colab after installing the project.

# importing needed modules
import torch
import json
import re
import ast

import pandas as pd
import numpy as np

#from research.ai_agents.environments.environment_simulation import StaticEnvironment
from research.paths import ENVIRONMENT_DATASET_PATH
from datasets import load_dataset
from trl import SFTTrainer
from trl import GRPOTrainer, GRPOConfig
from transformers import TrainingArguments
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from peft import PeftModel
from tqdm import tqdm
from google.colab import files

/content/AI_agents_mini_project/src/research/ai_agents/environment/evaluation.py:22: SyntaxWarning: invalid escape sequence '\d'
  the file: research\datasets\environment_datasets\toolmeta.json.

## Environment and Dataset

The GTA benchmark consists of 209 tool agent tasks annotated with their respective correct goal reaching sequence of thoughts and actions. For each task the agent is provided with a different set of tools and inputs and is required to answer a question or do a task in a few number of steps using exclusively the provided tools.

The reasonning process to reach the goal can be relatively complex for small language models (SLMs) as it requires gathering relevant information first using different tools and then combining the results in the correct way to reach the goal.

This benchmark provides an adequate experimental framework for our "mini-experiment" on SLM based Ai agents because it is adapted to our limited computaional resources and the environment configuration using this benchmark is easy and time efficient.

#### Clear GTA Dataset

In [ ]:
clear_gta_path = ENVIRONMENT_DATASET_PATH / "GTA_dataset" / "tasks.csv"
clear_gta_df = pd.read_csv(clear_gta_path)
clear_gta_df.head()

,Unnamed: 0,input,instruction,tools,final_answer,tool_calls
0,0,"[{'image_path': 'image/image_1.jpg', 'image_de...",How much should I pay for the beer on the tabl...,"[{""name"": ""OCR"", ""description"": ""This tool can...",[['12']],"{""CountGivenObject"": [{""arguments"": {""image"": ..."
1,1,"[{'image_path': 'image/image_3.jpg', 'image_de...",I want to buy a PS5 for each child in the phot...,"[{""name"": ""Calculator"", ""description"": ""A calc...",[['1919.96']],"{""CountGivenObject"": [{""arguments"": {""image"": ..."
2,2,"[{'image_path': 'image/image_7.jpg', 'image_de...",How many cups of water do the people in the p...,"[{""name"": ""Calculator"", ""description"": ""A calc...",[['27']],"{""OCR"": [{""arguments"": {""image"": ""image/image_..."
3,3,"[{'image_path': 'image/image_9.jpg', 'image_de...",I need to prepare twelve servings of this dis...,"[{""name"": ""OCR"", ""description"": ""This tool can...",[['2']],"{""OCR"": [{""arguments"": {""image"": ""image/image_..."
4,4,"[{'image_path': 'image/image_11.jpg', 'image_d...",I want to buy a dog toy for each dog in the p...,"[{""name"": ""Calculator"", ""description"": ""A calc...",[['79.96']],"{""OCR"": [{""arguments"": {""image"": ""image/image_..."

#### Finetuning Dataset

In [ ]:
# Load dataset
finetuning_dataset_path = ENVIRONMENT_DATASET_PATH / "GTA_dataset" / "finetuning_dataset.jsonl"
dataset = load_dataset("json", data_files={"train": str(finetuning_dataset_path)})
ds = dataset["train"]
dataset_df = ds.select(range(5)).to_pandas()
print("Dataset overview:")
dataset_df.head()

Generating train split: 0 examples [00:00, ? examples/s]

Dataset overview:

,prompt,completion,task_id
0,"[{'role': 'system', 'content': 'You are an exp...","[{'role': 'assistant', 'content': 'Thought: Th...",0
1,"[{'role': 'system', 'content': 'You are an exp...","[{'role': 'assistant', 'content': 'Thought: No...",0
2,"[{'role': 'system', 'content': 'You are an exp...","[{'role': 'assistant', 'content': 'Thought: No...",0
3,"[{'role': 'system', 'content': 'You are an exp...","[{'role': 'assistant', 'content': 'Action: {'n...",0
4,"[{'role': 'system', 'content': 'You are an exp...","[{'role': 'assistant', 'content': 'Thought: To...",1

In [ ]:
GROUP_COL = "task_id"
SEED = 42

# split by unique group ids, then select rows by indices
def split_by_group(ds, group_col, test_size, seed):
    # Get all group ids
    group_values = ds[group_col]
    unique_groups = np.array(sorted(set(group_values)))

    rng = np.random.default_rng(seed)
    rng.shuffle(unique_groups)

    n_test_groups = int(round(len(unique_groups) * test_size))
    test_groups = set(unique_groups[:n_test_groups])
    train_groups = set(unique_groups[n_test_groups:])

    # Build row indices for each split
    train_idx = [i for i, g in enumerate(group_values) if g in train_groups]
    test_idx  = [i for i, g in enumerate(group_values) if g in test_groups]

    return ds.select(train_idx), ds.select(test_idx)


# Split into train/test with disjoint task_ids
train_dataset, test_dataset = split_by_group(
    ds, GROUP_COL, test_size=0.4, seed=SEED
)

# Split train into SFT vs GRPO with disjoint task_ids
sft_train_dataset, grpo_train_dataset = split_by_group(
    train_dataset, GROUP_COL, test_size=0.5, seed=SEED
)

# Display lengths
print(f"Train dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")
print(f"SFT train dataset size: {len(sft_train_dataset)}")
print(f"GRPO train dataset size: {len(grpo_train_dataset)}")

# Display task ids for each split
sft_group_values = sft_train_dataset[GROUP_COL]
sft_tasks = np.array(sorted(set(sft_group_values)))
print(f"\n SFT task ids: \n{sft_tasks}")

grpo_group_values = grpo_train_dataset[GROUP_COL]
grpo_tasks = np.array(sorted(set(grpo_group_values)))
print(f"\n GRPO task ids: \n{grpo_tasks}")

train_group_values = train_dataset[GROUP_COL]
train_tasks = np.array(sorted(set(train_group_values)))
print(f"\n All train task ids: \n{train_tasks}")

test_group_values = test_dataset[GROUP_COL]
test_tasks = np.array(sorted(set(test_group_values)))
print(f"\n All test task ids: \n{test_tasks}")

Train dataset size: 406
Test dataset size: 266
SFT train dataset size: 203
GRPO train dataset size: 203

 SFT task ids:
['1' '11' '112' '114' '118' '119' '125' '126' '13' '134' '135' '141' '142'
 '146' '15' '151' '152' '153' '156' '157' '160' '162' '164' '165' '169'
 '172' '173' '180' '181' '182' '188' '190' '193' '196' '197' '198' '199'
 '202' '205' '212' '216' '219' '221' '224' '225' '227' '27' '33' '37' '38'
 '4' '40' '46' '54' '55' '56' '58' '63' '64' '7' '77' '78' '8' '80' '86'
 '90' '91' '94' '98']

 GRPO task ids:
['0' '102' '103' '107' '108' '110' '111' '113' '115' '117' '129' '130'
 '133' '136' '137' '138' '139' '140' '150' '154' '155' '167' '168' '175'
 '177' '18' '186' '191' '20' '200' '203' '206' '208' '209' '210' '214'
 '22' '220' '222' '223' '226' '23' '24' '25' '3' '30' '34' '36' '42' '43'
 '50' '51' '52' '57' '59' '66' '67' '68' '69' '70' '71' '72' '74' '82'
 '83' '84' '85' '97']

 All train task ids:
['0' '1' '102' '103' '107' '108' '11' '110' '111' '112' '113' '114' '115'
 '117' '118' '119' '125' '126' '129' '13' '130' '133' '134' '135' '136'
 '137' '138' '139' '140' '141' '142' '146' '15' '150' '151' '152' '153'
 '154' '155' '156' '157' '160' '162' '164' '165' '167' '168' '169' '172'
 '173' '175' '177' '18' '180' '181' '182' '186' '188' '190' '191' '193'
 '196' '197' '198' '199' '20' '200' '202' '203' '205' '206' '208' '209'
 '210' '212' '214' '216' '219' '22' '220' '221' '222' '223' '224' '225'
 '226' '227' '23' '24' '25' '27' '3' '30' '33' '34' '36' '37' '38' '4'
 '40' '42' '43' '46' '50' '51' '52' '54' '55' '56' '57' '58' '59' '63'
 '64' '66' '67' '68' '69' '7' '70' '71' '72' '74' '77' '78' '8' '80' '82'
 '83' '84' '85' '86' '90' '91' '94' '97' '98']

 All test task ids:
['10' '100' '101' '104' '105' '106' '109' '116' '12' '120' '121' '122'
 '123' '124' '127' '128' '131' '132' '14' '143' '144' '145' '147' '148'
 '149' '158' '159' '16' '161' '163' '166' '17' '170' '171' '174' '176'
 '178' '179' '183' '184' '185' '187' '189' '19' '192' '194' '195' '2'
 '201' '204' '207' '21' '211' '213' '215' '217' '218' '228' '26' '28' '29'
 '31' '32' '35' '39' '41' '44' '45' '47' '48' '49' '5' '53' '6' '60' '61'
 '62' '65' '73' '75' '76' '79' '81' '87' '88' '89' '9' '92' '93' '95' '96'
 '99']

## Supervized finetuning on 50% of training dataset

In [ ]:
def load_base(model_name):
    # 4-bit quantization config (QLoRA)
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float16,
    )
    base = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float16,
    )
    base.config.use_cache = False
    base = prepare_model_for_kbit_training(base)
    return base

In [ ]:
model_name = "Qwen/Qwen2.5-1.5B-Instruct"

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# load quantized model
model = load_base(model_name)

# LoRA config
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)

# Attach LoRA adapter
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Training arguments
training_args = TrainingArguments(
    output_dir="./out_sft",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    num_train_epochs=5,
    logging_steps=10,
    save_strategy="no",
    save_total_limit=2,
    bf16=torch.cuda.is_available(),
    fp16=not torch.cuda.is_available(),
    optim="paged_adamw_8bit",
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    report_to="none",
)

trainable params: 18,464,768 || all params: 1,562,179,072 || trainable%: 1.1820

In [ ]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=sft_train_dataset,
)
trainer.train()
trainer.save_model("./out_sft/final")

/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:2111: FutureWarning: `--push_to_hub_token` is deprecated and will be removed in version 5 of 🤗 Transformers. Use `--hub_token` instead.
  warnings.warn(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1044: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

In [ ]:
!zip -r ./out_sft.zip ./out_sft
files.download('./out_sft.zip')

  adding: out_sft/ (stored 0%)
  adding: out_sft/final/ (stored 0%)
  adding: out_sft/final/README.md (deflated 65%)
  adding: out_sft/final/merges.txt (deflated 57%)
  adding: out_sft/final/special_tokens_map.json (deflated 69%)
  adding: out_sft/final/vocab.json (deflated 61%)
  adding: out_sft/final/added_tokens.json (deflated 67%)
  adding: out_sft/final/adapter_config.json (deflated 58%)
  adding: out_sft/final/tokenizer.json (deflated 81%)
  adding: out_sft/final/chat_template.jinja (deflated 71%)
  adding: out_sft/final/adapter_model.safetensors (deflated 22%)
  adding: out_sft/final/training_args.bin (deflated 52%)
  adding: out_sft/final/tokenizer_config.json (deflated 89%)